resources:
- name: bpm-release
  type: git
  source:
    branch: master
    private_key: ((bpm-github-deploy-key))
    uri: git@github.com:cloudfoundry-incubator/bpm-release.git

- name: bosh-ecosystem-docker-image
  type: docker-image
  source:
    repository: bosh/bosh-ecosystem-concourse
    username: ((docker.username))
    password: ((docker.password))

- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    days: [Saturday]

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release
    branch: master
    paths:
      - releases/golang

- name: version
  type: semver
  source:
    driver: gcs
    bucket: bpm-release-version
    key: current-version
    initial_version: 0.0.0
    json_key: ((bpm-version-gcs-json-key))

- name: boshlite-bionic-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-bionic-go_agent

- name: boshlite-xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent

- name: runc-linux
  type: github-release
  check_every: 24h
  source:
    owner: opencontainers
    repository: runc
    pre_release: true
    access_token: ((bpm-machine-github-token))
    order_by: time # without this v1.0.0-rc9 > v1.0.0-rc10

- name: tini
  type: github-release
  check_every: 24h
  source:
    owner: krallin
    repository: tini
    access_token: ((bpm-machine-github-token))

- name: bpm-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bpm-release
    branch: master
    paths: [ci/Dockerfile]
    private_key: ((bpm-github-deploy-key))

- name: bpm-ci-image
  type: docker-image
  source:
    repository: cfbpm/bpm-ci
    username: ((docker-username))
    email: ((docker-email))
    password: ((docker-password))

- name: golang-image
  type: docker-image
  source:
    repository: golang

- name: daily
  type: time
  source:
    interval: 24h

- name: bpm-bosh-io
  type: bosh-io-release
  source:
    repository: cloudfoundry/bpm-release

jobs:
- name: test-unit
  plan:
  - get: bpm-release
    trigger: true
  - task: test-unit
    file: bpm-release/ci/test-unit.yml
    privileged: true

- name: test-acceptance-bionic
  plan:
  - in_parallel:
    - get: bpm-release
      trigger: true
    - get: boshlite-bionic-stemcell
      trigger: true
  - task: test-acceptance
    file: bpm-release/ci/test-acceptance.yml
    params:
      STEMCELL_NAME: ubuntu-bionic
    input_mapping:
      bosh-stemcell: boshlite-bionic-stemcell
    privileged: true

- name: test-acceptance-xenial
  plan:
  - in_parallel:
    - get: bpm-release
      trigger: true
    - get: boshlite-xenial-stemcell
      trigger: true
  - task: test-acceptance
    file: bpm-release/ci/test-acceptance.yml
    params:
      STEMCELL_NAME: ubuntu-xenial
    input_mapping:
      bosh-stemcell: boshlite-xenial-stemcell
    privileged: true

- name: test-upgrade
  plan:
  - in_parallel:
    - get: bpm-release
      trigger: true
    - get: boshlite-xenial-stemcell
      trigger: true
    - get: bpm-bosh-io
  - task: test-acceptance
    file: bpm-release/ci/test-upgrade.yml
    params:
      STEMCELL_NAME: ubuntu-xenial
    input_mapping:
      bosh-stemcell: boshlite-xenial-stemcell
    privileged: true

- name: bump-golang-package
  serial: true
  plan:
    - in_parallel:
        - get: bosh-ecosystem-docker-image
        - get: bpm-release
        - get: golang-release
          trigger: true
        - get: bosh-stemcell
          resource: boshlite-bionic-stemcell
    - task: bump-golang-package
      file: bpm-release/ci/tasks/bump-golang-package.yml
      image: bosh-ecosystem-docker-image
      params:
        BOSH_PRIVATE_CONFIG: ((bpm-private-yml))
    - task: test-acceptance
      file: bpm-release/ci/test-acceptance.yml
      params:
        STEMCELL_NAME: ubuntu-bionic
      privileged: true
    - put: bpm-release
      params:
        repository: bpm-release
        rebase: true

- name: bump-patch
  serial_groups:
  - version
  plan:
  - get: version
    passed:
    params:
      bump: patch
  - put: version
    params:
      file: version/version

- name: bump-minor
  serial_groups:
  - version
  plan:
  - get: version
    params:
      bump: minor
  - put: version
    params:
      file: version/version

- name: bump-major
  serial_groups:
  - version
  plan:
  - get: version
    params:
      bump: major
  - put: version
    params:
      file: version/version

- name: create-final-release
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: bpm-release
      passed:
      - test-acceptance-bionic
      - test-acceptance-xenial
      - test-unit
      - test-upgrade
    - get: version
      params:
        bump: final
  - task: bump-local-version
    file: bpm-release/ci/bump-local-version.yml
  - task: finalize-release
    file: bpm-release/ci/finalize-release.yml
    input_mapping:
      bpm-release: release-repo
    params:
      RELEASE_NAME: bpm
      BLOBSTORE_PRIVATE_YML: ((bpm-private-yml))
  - put: bpm-release
    get_params:
      submodules: none
    params:
      repository: final-release-repo
      submodules: none
      rebase: true
      tag: version/version
      tag_prefix: v
  - task: bump-local-version
    file: bpm-release/ci/bump-local-version.yml
    input_mapping:
      bpm-release: final-release-repo
    params:
      DEV: true
  - put: bpm-release
    get_params:
      submodules: none
    params:
      repository: release-repo
      submodules: none
      rebase: true

- name: bump-deps
  public: true
  plan:
    - get: weekly
      trigger: true
    - get: bpm-release
    - task: bump-deps
      params:
        BOSH_PRIVATE_CONFIG: ((bpm-private-yml))
      file: bpm-release/ci/tasks/bumps-deps.yml
    - task: test-runc-update
      file: bpm-release/ci/test-runc-update.yml
      params:
        BOSH_PRIVATE_CONFIG: ((bpm-private-yml))
      privileged: true
    - put: bpm-release
      params:
        repository: bumped-bpm-release

- name: build-bpm-ci
  serial: true
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: bpm-ci
      trigger: true
      attempts: 3
    - get: golang-image
      trigger: true
      attempts: 3
      params: {save: true}
    - get: runc-linux
      trigger: true
      attempts: 3
    - get: tini
      trigger: true
      attempts: 3
      params:
        globs:
        - tini-amd64
  - put: bpm-ci-image
    attempts: 3
    params:
      load_base: golang-image
      build: .
      dockerfile: bpm-ci/ci/Dockerfile
