#!/usr/bin/env bash

set -e

VERSION="$(cat version/version)"
RELEASE_TGZ="${PWD}/bpm-rc/bpm-${VERSION}.tgz"

pushd bpm-release/
  # work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
  # into release dir, which is invalid cross-device link
  export HOME=$PWD

  bosh -n create-release \
    --name bpm \
    --version "$VERSION" \
    --tarball $RELEASE_TGZ
popd
