---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
- name: bpm-release
- name: version

outputs:
- name: release-repo

params:
  DEV: ~

run:
  path: bpm-release/ci/tasks/bump-local-version
