---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/bosh/docker-cpi
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))

inputs:
- name: bpm-release
- name: bpm-bosh-io
- name: bosh-stemcell

params:
  STEMCELL_NAME: ubuntu-noble

run:
  path: bpm-release/scripts/test-upgrade
