---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/bosh/docker-cpi
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))

inputs:
- name: bpm-release
- name: bosh-stemcell

params:
  STEMCELL_NAME:
  # true to also run the specs against the stemcell's system install of bpm
  TEST_SYSTEM_INSTALL: false

run:
  path: bpm-release/ci/tasks/test-acceptance.sh
