---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/docker-cpi

inputs:
- name: bpm-release
- name: bpm-bosh-io
- name: bosh-stemcell

params:
  STEMCELL_NAME: ubuntu-jammy

run:
  path: bpm-release/scripts/test-upgrade
