#!/bin/bash

absolute_path() {
  (cd "$1" && pwd)
}

scripts_path=$(absolute_path "$(dirname "$0")" )

sudo docker run \
  --privileged \
  -v  ${scripts_path}/..:/crucible \
  -e "GOPATH=/crucible" \
  -it pcfsecurity/crucible-ci:latest \
  /bin/bash -c 'export PATH=$PATH:$GOPATH/bin; /bin/bash'
