#!/bin/bash

absolute_path() {
  (cd "$1" && pwd)
}

scripts_path=$(absolute_path "$(dirname "$0")" )

sudo docker pull pcfsecurity/bpm-ci:latest

sudo docker run \
  --privileged \
  -v  ${scripts_path}/..:/bpm \
  -e "GOPATH=/bpm" \
  -it pcfsecurity/bpm-ci:latest \
  /bin/bash -c 'export PATH=$PATH:$GOPATH/bin; /bin/bash'
