#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list  -app bpm/...
  gosub list -test bpm/...
  gosub list  -app bpm/acceptance/...
  gosub list -test bpm/acceptance/...
} | grep -v fakes | xargs gosub sync
