#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list  -app crucible/...
  gosub list -test crucible/...
  gosub list  -app crucible-acceptance/...
  gosub list -test crucible-acceptance/...
} | xargs gosub sync
