#!/usr/bin/env bash
set -euo pipefail

RELEASE_PATH="$(cd "$(dirname "$0")/.." && pwd)"
export RELEASE_PATH

FLY_TARGET=${FLY_TARGET:-ci}

fly -t "${FLY_TARGET}" execute -p -c "${RELEASE_PATH}/ci/test-unit.yml" "$@"
