#!/usr/bin/env bash

set -eux

start-bosh

source /tmp/local-bosh/director/env

bosh upload-stemcell bosh-stemcell/*.tgz

bosh create-release \
  --dir "$PWD/crucible/"

bosh upload-release \
  --dir "$PWD/crucible/"

export BOSH_DEPLOYMENT=crucible
export BOSH_NON_INTERACTIVE=true

bosh deploy \
  "$PWD/crucible/example-manifests/bosh-lite-ci.yml"

export GOPATH="$PWD/crucible"
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

# This is the IP of the first VM in the bosh in the concourse container.
# It will not change unless we deploy more instances/jobs etc or the upstream
# docker image changes its cloudconfig.
AGENT_HOST="${AGENT_HOST:-"10.245.0.2"}"
agent_port=1337

pushd "${GOPATH}/src/crucible-acceptance" > /dev/null
  ginkgo -r -p -race -randomizeAllSpecs -- --agent-uri="http://${AGENT_HOST}:${agent_port}/"
popd > /dev/null
