#!/usr/bin/env bash
set -euo pipefail

set -x

RELEASE_PATH="$(cd "$(dirname "$0")/.." && pwd)"
export RELEASE_PATH

. start-bosh

source /tmp/local-bosh/director/env

export BOSH_DEPLOYMENT=bpm
export BOSH_NON_INTERACTIVE=true

bosh upload-stemcell bosh-stemcell/*.tgz

echo "Deploying latest final version of bpm"
bosh upload-release bpm-bosh-io/*.tgz
bosh deploy \
  "${RELEASE_PATH}/manifests/bosh-lite-ci.yml" \
  -v "stemcell_name=${STEMCELL_NAME}"

echo "Deploying latest dev version of bpm"
bosh create-release --dir "${RELEASE_PATH}/" --timestamp-version
bosh upload-release --dir "${RELEASE_PATH}/"

"${RELEASE_PATH}/scripts/run-acceptance-specs"
