#!/usr/bin/env bash
set -euo pipefail

RELEASE_PATH="$(cd "$(dirname "$0")/.." && pwd)"
export RELEASE_PATH

pushd "${RELEASE_PATH}/src/bpm" > /dev/null
  go run github.com/onsi/ginkgo/v2/ginkgo -r -p --race --randomize-all --skip-package "acceptance" "$@"
popd
