#!/usr/bin/env bash
set -euo pipefail

set -x

RELEASE_PATH="$(cd "$(dirname "$0")/.." && pwd)"
export RELEASE_PATH

. start-bosh

source /tmp/local-bosh/director/env

export BOSH_DEPLOYMENT=bpm
export BOSH_NON_INTERACTIVE=true

bosh upload-stemcell bosh-stemcell/*.tgz

bosh create-release --dir "${RELEASE_PATH}/"
bosh upload-release --dir "${RELEASE_PATH}/"

"${RELEASE_PATH}/scripts/run-acceptance-specs"
