#!/usr/bin/env bash

set -eux

start-bosh

source /tmp/local-bosh/director/env

bosh upload-stemcell bosh-stemcell/*.tgz

bosh create-release \
  --dir "$PWD/bpm-release/"

bosh upload-release \
  --dir "$PWD/bpm-release/"

export BOSH_DEPLOYMENT=bpm
export BOSH_NON_INTERACTIVE=true

bosh deploy \
  "$PWD/bpm-release/example-manifests/bosh-lite-ci.yml" \
  -v "stemcell_name=${STEMCELL_NAME}"

export GOPATH="$PWD/bpm-release"
export PATH=$GOPATH/bin:$PATH

go install bpm/vendor/github.com/onsi/ginkgo/ginkgo

AGENT_HOST="$(bosh -d bpm instances | grep running | awk '{ print $4 }')"
agent_port=1337

pushd "${GOPATH}/src/bpm/acceptance" > /dev/null
  ginkgo -r -p -race -randomizeAllSpecs -- --agent-uri="http://${AGENT_HOST}:${agent_port}"
popd > /dev/null
