#!/usr/bin/env bash
set -euo pipefail

RELEASE_PATH="$(cd "$(dirname "$0")/.." && pwd)"
export RELEASE_PATH

. "${RELEASE_PATH}/scripts/checkdocker.sh"

if user_can_docker; then
  DOCKER="docker"
else
  # On development workstations docker must run as root.
  # These settings are not related to the privileges that bpm creates runc containers with.
  DOCKER="sudo docker"
fi

$DOCKER pull cfbpm/bpm-ci:latest

$DOCKER run \
  --privileged \
  -v "${RELEASE_PATH}:/bpm" \
  -t cfbpm/bpm-ci:latest \
  /bpm/scripts/test-unit "$@"
