#!/bin/bash

set -e

absolute_path() {
  (cd "$1" && pwd)
}

scripts_path=$(absolute_path "$(dirname "$0")" )

export GOPATH=$scripts_path/..
export PATH=$GOPATH/bin:$PATH

pushd "${GOPATH}" > /dev/null
  pushd "src/bpm" > /dev/null
    go install ./vendor/github.com/onsi/ginkgo/ginkgo
    go install ./vendor/github.com/maxbrunsfeld/counterfeiter
  popd > /dev/null

  pushd "src/bpm" > /dev/null
    go generate ./...
    ginkgo -r -p -race -randomizeAllSpecs -skipPackage "acceptance" "$@"
  popd > /dev/null
popd
